/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.BarangController;

/**
 *
 * @author Novil F
 */
public class EditBarang extends javax.swing.JFrame {
    
    BarangController controller = new BarangController();

    /**
     * Creates new form TambahBarang
     */
    public EditBarang() {
        initComponents();
        
        controller.tampilKodeBarang(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelJudul = new javax.swing.JLabel();
        labelMerkBarang = new javax.swing.JLabel();
        comboBoxKodeBarang = new javax.swing.JComboBox();
        labelJumlah = new javax.swing.JLabel();
        spinnerJumlah = new javax.swing.JSpinner();
        spinnerHarga = new javax.swing.JSpinner();
        labelHarga = new javax.swing.JLabel();
        comboBoxStaff = new javax.swing.JComboBox();
        labelStaff = new javax.swing.JLabel();
        buttonEditBarang = new javax.swing.JButton();
        buttonBatal = new javax.swing.JButton();
        labelKodeBarang = new javax.swing.JLabel();
        textMerkBarang = new javax.swing.JTextField();
        comboBoxPemasok = new javax.swing.JComboBox();
        labelPemasok = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelJudul.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelJudul.setText("Edit Barang");

        labelMerkBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMerkBarang.setText("Nama / Merk");

        comboBoxKodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxKodeBarangActionPerformed(evt);
            }
        });

        labelJumlah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelJumlah.setText("Jumlah");

        labelHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelHarga.setText("Harga");

        comboBoxStaff.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Eddy Gunawan", "Rafi Akbar", "Haikal Mahardika" }));

        labelStaff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelStaff.setText("Staff");

        buttonEditBarang.setText("Edit");
        buttonEditBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditBarangActionPerformed(evt);
            }
        });

        buttonBatal.setText("Batal");

        labelKodeBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeBarang.setText("Kode Barang");

        comboBoxPemasok.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PT. Gunajaya", "PT. Makmur Mahakam", "PT. Bursa Borneo" }));

        labelPemasok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPemasok.setText("Pemasok");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxStaff, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spinnerHarga, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spinnerJumlah, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                        .addComponent(buttonEditBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textMerkBarang)
                    .addComponent(comboBoxPemasok, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addComponent(labelJudul))
                            .addComponent(labelMerkBarang)
                            .addComponent(labelJumlah)
                            .addComponent(labelHarga)
                            .addComponent(labelStaff)
                            .addComponent(labelKodeBarang)
                            .addComponent(labelPemasok))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(comboBoxKodeBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(labelKodeBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelMerkBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textMerkBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPemasok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelJumlah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelHarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelStaff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEditBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEditBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditBarangActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buttonEditBarangActionPerformed

    private void comboBoxKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxKodeBarangActionPerformed
        // TODO add your handling code here:
        controller.tampilInfoBarang(this);
    }//GEN-LAST:event_comboBoxKodeBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonEditBarang;
    public javax.swing.JComboBox comboBoxKodeBarang;
    public javax.swing.JComboBox comboBoxPemasok;
    public javax.swing.JComboBox comboBoxStaff;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelJumlah;
    private javax.swing.JLabel labelKodeBarang;
    private javax.swing.JLabel labelMerkBarang;
    private javax.swing.JLabel labelPemasok;
    private javax.swing.JLabel labelStaff;
    public javax.swing.JSpinner spinnerHarga;
    public javax.swing.JSpinner spinnerJumlah;
    public javax.swing.JTextField textMerkBarang;
    // End of variables declaration//GEN-END:variables
}
